version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.9.0
    container_name: al-folio-website
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=9080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 9080:9080
    volumes:
      - .:/srv/jekyll